name: Vercel Production Deployment

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  Deploy-Backend:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check sh availability
        run: sh --version

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Set Backend Vercel Project ID
        run: echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_BACKEND_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Pull Vercel Environment Information for Backend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --cwd ./server

      - name: Build Backend Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd ./server

      - name: Deploy Backend Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd ./server

  Deploy-Frontend:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check sh availability
        run: sh --version

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Set Frontend Vercel Project ID
        run: echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Pull Vercel Environment Information for Frontend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --cwd ./client

      - name: Build Frontend Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd ./client

      - name: Deploy Frontend Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd ./client
