name: Vercel Deployment (Client and Server)

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_FRONTEND_PROJECT_ID: ${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}
  VERCEL_BACKEND_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}

on:
  push:
    branches:
      - main

jobs:
  Deploy-Projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Pull Vercel Environment Information for Frontend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --project-id=${{ secrets.VERCEL_FRONTEND_PROJECT_ID }} --org-id=${{ secrets.VERCEL_ORG_ID }} --cwd client

      - name: Build Frontend Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --project-id=${{ secrets.VERCEL_FRONTEND_PROJECT_ID }} --org-id=${{ secrets.VERCEL_ORG_ID }} --cwd client

      - name: Deploy Frontend Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --project-id=${{ secrets.VERCEL_FRONTEND_PROJECT_ID }} --org-id=${{ secrets.VERCEL_ORG_ID }} --cwd client

      - name: Pull Vercel Environment Information for Backend
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --project-id=${{ secrets.VERCEL_BACKEND_PROJECT_ID }} --org-id=${{ secrets.VERCEL_ORG_ID }} --cwd server

      - name: Build Backend Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --project-id=${{ secrets.VERCEL_BACKEND_PROJECT_ID }} --org-id=${{ secrets.VERCEL_ORG_ID }} --cwd server

      - name: Deploy Backend Project Artifacts
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --project-id=${{ secrets.VERCEL_BACKEND_PROJECT_ID }} --org-id=${{ secrets.VERCEL_ORG_ID }} --cwd server
