name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  Deploy-Backend:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Frontend Directory
        run: |
          echo "Current Directory: $(pwd)"
          echo "Contents: $(ls -la)"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Set Backend Vercel Project ID
        run: echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_BACKEND_PROJECT_ID }}" >> $GITHUB_ENV
        

      - name: Pull Vercel Environment Information for Backend
        run: |
          echo "Running Vercel Pull in Current Directory: $(pwd)"
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --cwd ./server
          echo "Running Vercel Pull in Current Directory: $(pwd)"

      - name: Build Backend Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd ./server

      - name: Deploy Backend Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd ./server

  Deploy-Frontend:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    needs: Deploy-Backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Frontend Directory
        run: |
          echo "Current Directory: $(pwd)"
          echo "Contents: $(ls -la)"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Set Frontend Vercel Project ID
        run: echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_FRONTEND_PROJECT_ID }}" >> $GITHUB_ENV

      - name: Pull Vercel Environment Information for Frontend
        run: |
          echo "Running Vercel Pull in Current Directory: $(pwd)"
          vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} --cwd ./client
          echo "Running Vercel Pull in Current Directory: $(pwd)"

      - name: Build Frontend Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd ./client

      - name: Deploy Frontend Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }} --cwd ./client
